### ISSUE TITLE
Support for json based grammar files

### ISSUE THREAD

**Issue by emoon** [edbee/edbee-lib#101]
Hi,

When looking around for some missing syntax files (in this case Rust) it seems that many uses json these days instead of the current xml based files that are in used by edbee. For example this

https://github.com/dunstontc/vscode-rust-syntax/blob/master/syntaxes/rust.tmLanguage.json

Any plans of supporting that?

Cheers!

**Comment by gamecreature** [comment]
I will look into this. If the format is just json instead of xml it shouldn't be very hard to implement.

**Comment by emoon** [comment]
That would be great :) It seems more common people uses json these days.

**Comment by gamecreature** [comment]
Note: The rust sample gives a warning.
It cannot find #unsorted definitions. (But it seems to color the rust files correctly)

**Comment by emoon** [comment]
Sweet! I noticed there is this directory also https://github.com/dunstontc/vscode-rust-syntax/tree/master/src/syntax but I'm not sure how this is connected to the syntax file above (I don't really use vs code)

**Comment by gamecreature** [comment]
I don't know for sure, but it somehow looks like it 'builds' it's json syntax file from multiple json5 sources.

**Comment by emoon** [comment]
Yeah it does seem so when I look closer. It seems most info is stuffed inside the `tmLanguage.json` file so it should all be fine I guess.
