### ISSUE TITLE
Add lineHeight to TextMarginComponentDelegate

### ISSUE THREAD

**Issue by emoon** [edbee/edbee-lib#103]
I'm trying to using `TextMarginComponentDelegate` to render breakpoint markers (and stepper) but there is no access to the line height inside so it's not possible to figure out how to render things on each line.

My suggestion is to add `int LineHeight` to `renderBefore` and `renderAfter`. I can do a PR for this if it sounds like a good idea (or if there are some other suggestion on how to make it)

**Comment by gamecreature** [comment]
Hi @emoon, If you look at the code at:

https://github.com/edbee/edbee-lib/blob/d946f680e887406e69b95f43adb4b404859424c4/edbee-lib/edbee/views/components/textmargincomponent.cpp#L293

You see the usage of lineHeight. 
The `TextMarginComponentDelegate` can access this with:

```c++
marginComponent()->renderer();
```

**Comment by emoon** [comment]
Thanks! Something I noticed in the `lineHegiht()` code is a comment of caching the value. I think that would be a good idea indeed :)
