### ISSUE TITLE
latest head fails to compile on OpenSUSE tumbleweed. round not declared.

### ISSUE THREAD

**Issue by breakone9r** [edbee/edbee-lib#106]
```
/home/abuild/rpmbuild/SOURCES/edbee-lib-1595879074.d946f68/edbee-lib/edbee/views/textrenderer.cpp: In member function 'int edbee::TextRenderer::xPosForColumn(int, int)':
[   77s] /home/abuild/rpmbuild/SOURCES/edbee-lib-1595879074.d946f68/edbee-lib/edbee/views/textrenderer.cpp:200:12: error: 'round' was not declared in this scope; did you mean 'qBound'?
[   77s]   200 |     return round(x);
[   77s]       |            ^~~~~
[   77s]       |            qBound
[   77s] make[2]: *** [edbee-lib/CMakeFiles/edbee-lib.dir/build.make:1047: edbee-lib/CMakeFiles/edbee-lib.dir/edbee/views/textrenderer.cpp.o] Error 1
```

**Comment by gamecreature** [comment]
@breakone9r could you check if this fix works for you?
Thanks!

**Comment by sebcaux** [comment]
Hi @gamecreature,
I've already fixed this small issue with some others and various improvements on our fork :
https://github.com/edbee/edbee-lib/compare/master...UniSwarm:master
But I don't know how to do pull requests that makes sense now.

**Comment by breakone9r** [comment]
@gamecreature Yes. That seems to fix it. Now there's a different problem, as the test is failing to find the includes. I'll look at that a bit, as I've seen a similar error before, and I'll create a new issue for it in a bit. This one can now be marked closed! Thanks a bunch.
