### ISSUE TITLE
edbee-lib fails to compile on Windows

### ISSUE THREAD

**Issue by keneanung** [edbee/edbee-lib#11]
Since updating `onig` in commit f04111fc56d3743de3b424431a9d25b871cf4151, the windows builds fail for qmake and gcc. The prepared cmake compilation and clang were not tested.

The reason seems to be that the windows version of `config.h` is not correctly included. We managed to work around this issue by adding the following to the `config.h` file
```c
#if _WIN32
  #include "win32/config.h"
#else
// ...
#endif
```

I'm not sure if that's a correct solution or what would be preferred, so I'll leave this as an issue.

**Comment by gamecreature** [comment]
Hope this fixes the issue

**Comment by keneanung** [comment]
That seems to be working!

**Comment by keneanung** [comment]
Multiple issues with the commit and the following merge:
1. Linux and macOS builds fail now (see travis)
2. The merge commit letsthe changes of commits e31637244f7d49df1e3f59f7cb63198127dd973d and d52393246b963ed8979378324fc43f7a9c6f983f disappear

**Comment by gamecreature** [comment]
I've had some issues with git. I'm using edbee in different projects and in one project the git repos had issues and was incorrectly merged. 
I've pushed and discarded some changes to github (so please check if your repos is still ok)

**Comment by keneanung** [comment]
:+1: travis compiles again and windows seems to work as well (I'm just waiting for an explicit okay before closing)

**Comment by vadi2** [comment]
Thanks for getting it sorted out so quick guys :)
