### ISSUE TITLE
[Fail to build] Uses feature only available since Qt 5.14

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#112]
Um, can you please put a workaround for the use of `(QTextStream&) Qt::endl(QTextStream &stream`? That is only available from Qt 5.**14** according to: https://doc.qt.io/qt-5/qt.html#end, however Qt 5.**12** (the LTS version) does not reach EOL until the end of next year (2021-12-05).

This is causing problems for projects (like Mudlet) that is using your library and which provides coverage for less than bloody-edged versions of Qt (some Linux distributions do not revise their system Qt version just because a new one is out!)

https://github.com/Mudlet/Mudlet/pull/4198

**Comment by gamecreature** [comment]
Just pushed a new commit which simply uses '\n'...
No deprecations and no issues with 5.12 
Please let me now if you run into more issues.  Thanks!

**Comment by SlySven** [comment]
It seems to work for us now, so closing this issue.

**Comment by vadi2** [comment]
Thanks a lot!
