### ISSUE TITLE
Double-click + drag should end at word boundaries

### ISSUE THREAD

**Issue by ethorondil** [edbee/edbee-lib#114]
If you double-click in edbee, it selects a word.  This is standard across editors.  But in most editors, if you double click and then drag the mouse, you continue to select sequences of words -- the left and right endpoints are expanded to include words.  In edbee it gives strange behavior (the right endpoint is directly under the cursor, the left endpoint is the left end of the initial word).

Also, triple-click should let you select sequences of lines.

**Comment by gamecreature** [comment]
I agree edbee should behave like other editors. 
Thanks for noticing!

**Comment by gamecreature** [comment]
Now it behaves correctly
