### ISSUE TITLE
Missing `case MoveCaretToWordBoundary:` in `switch`  statement

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#119]
https://github.com/edbee/edbee-lib/blob/e75348de90663ec10603d4264d1e75e9e9206650/edbee-lib/edbee/commands/selectioncommand.cpp#L178

You need to add code to handle the missing `case` of `MoveCaretToWordBoundary`...

**Comment by gamecreature** [comment]
Thanks @SlySven  !!
