### ISSUE TITLE
Wrap QTextLayout rendering/positioning calculations, to support 'virtual' characters.

### ISSUE THREAD

**Issue by gamecreature** [edbee/edbee-lib#128]
Currently Edbee uses QTextLayout, QTextLine directly to render and calculate cursor positions directly.
QTextLayout doesn't seem to support text-parts (like [u+2204]), which acts like a 'virtual character'. 

(If somebody knows QTextLayout can do this, please let me know!!)

A workaround for this could be a wrapper class build around QTextLayout, which forces virtual positioning. (For example required by #127).

This adds support for rending a single character as number of characters. While keeping caret/cursor support valid. 

![image](https://user-images.githubusercontent.com/577933/143597869-9406310c-c876-41f7-b287-1d38d5ba0eb6.png)

**Comment by gamecreature** [comment]
@vadi2 This branch has support for the above rendering of special characters. I looks like it work correctly with carets/mouse etc..  Before merging this to the master branch I would appreciate it, if somebody can test if Mudlet still works with it. Thanks!

**Comment by gamecreature** [comment]
Note: The last commit is correct. (The other is replace via --amend)

**Comment by vadi2** [comment]
Yes! Will try it.

**Comment by vadi2** [comment]
Looks great to us!

Don't forget to add the new `textlayout.(cpp|h)` to cmake.

**Comment by gamecreature** [comment]
Added cmake and erged the branch! 
Thanks for testing (and reminding me to include cmake!)
