### ISSUE TITLE
How to disable shadows?

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#13]
Sublime uses shadows on elements that don't have distinct borders, like the minimap - but it doesn't use them on elements that do, like scrollbars. Edbee however uses them on scrollbars as well which is a little over the top for me - how can I disable the shadows?

**Comment by gamecreature** [comment]
Is just added a method to enable/disable the scrollarea shadows

```c++
widget->textScrollArea()->enableShadowWidget(bool)
```
This is no a complete solution. It would  nicer if I exposed the 'PrivateShadowWidget' as public interface. (This could enable the customization of the shadow rendering).

**Comment by vadi2** [comment]
Awesome, thanks!
