### ISSUE TITLE
Hard tab characters are now visible

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#130]

**Comment by vadi2** [comment]
Pressed enter too early... https://github.com/edbee/edbee-lib/commit/b8dc3558295b76fa8131c16e6a5a11c098f680a1 does a great job but it's also highlighting hard tab characters (if you press the `Tab` key) which makes code that uses them difficult to follow:

![image](https://user-images.githubusercontent.com/110988/142576226-9c231ebc-a2b8-4b55-9af6-08a9d50744d1.png)

**Comment by gamecreature** [comment]
Fixed id in Edbee (used bidicode example from VScode.. but it used charCode == 8 as tab-character. Changed it to charCode == 9)

**Comment by vadi2** [comment]
Confirmed fixed - tyvm.
