### ISSUE TITLE
Regression: Writing diacritics in Linux

### ISSUE THREAD

**Issue by Kebap** [edbee/edbee-lib#132]
#### Brief summary of issue:
You can't type any of these diacritics symbols on Linux: ```^ ` ´``` and therefore `âéù` etc.

#### Steps to reproduce the issue:

1. Press ^ key on your keyboard
2. Press ^ again just to make sure
3. No symbol is painted at all, at all

#### Error output / Expected result of feature
3. This should print ^ sign. (Depending on your setup this can even print ^^ twice)

#### Extra information:

Typing in other widgets works fine, just not in edbee editor text box area.

Tested in Windows: Works as expected. Only on Linux does not. Mac was not tested, yet.
Tested earlier version (Mudlet 4.10.1 from late 2019) in Linux: Works as expected. Version 4.11 (early 2020) until today do not anymore.

Movie of this in action:
![diacritics](https://user-images.githubusercontent.com/117238/149848211-35762276-e607-4494-8898-f86bb58527d8.gif)
Left window: Mudlet 4.14.1 - Right window: Mudlet 4.10 - both on Linux

**Comment by gamecreature** [comment]
@Kebap Do you have more info about your configuration. (I just installed Debian)
I can enter special characters: [ ' ]  + [ e ] =>  é, pressing [ ' ] [ ' ] => ' 
 
What distro do you use...
What keyboard layout etc??

**Comment by Kebap** [comment]
I actually have two reports here, one in Kubuntu, the other Linux Mint, both with German language settings.
Please let me know any diagnostic commands we should run to provide more detailed information to you.

**Comment by gamecreature** [comment]
Well `#ifndef Q_OS_LINUX`.. that explains why it isn't working 

https://github.com/edbee/edbee-lib/blob/d0987396629d0c62041af405c6c404b475139c67/edbee-lib/edbee/views/components/texteditorcomponent.cpp#L347-L350

But somehow this was required ... I will try to figure out what the issue was..

https://github.com/edbee/edbee-lib/commit/a95706d621e4610c5fe66a339bf9f9cea4c0a32d

**Comment by gamecreature** [comment]
OK found the discussion about this:  https://github.com/edbee/edbee-lib/commit/2b972507d8c60c76e325b3144e3809ae0cb70a69#commitcomment-41656637

**Comment by vadi2** [comment]
That makes sense, and that definitely fixed a worse issue...

**Comment by gamecreature** [comment]
@vadi2 I enabled it in my Linux VM, but it doesn't seem to cause any clear text on focus lost . 
But when I diff the code:

Old situation: (with the clear-selection issue)

```c++
    // replace the selection with an empty text
    if( textSelection()->hasSelection() ) {
        controller()->replaceSelection("",false);
    }
```

Current situation
```c++
#ifndef Q_OS_LINUX
    // replace the selection with an empty text (only if there's content to replace)
    if( textSelection()->hasSelection() && (!m->preeditString().isEmpty() || !m->commitString().isEmpty())) {
        controller()->replaceSelection("",false);
    }
```

The replaceSelection code has got more conditionals. When I add the first situation the selected text is indeed cleared.
The current seems to work correctly on my Linux platform.  I will remove the #ifdef Q_OS_LINUX and this should resolve both issues.

**Comment by vadi2** [comment]
Fantastic!

**Comment by SlySven** [comment]
:thinking: Would this be because the keys that are being used to create the accents are *dead-keys* i.e. you press them *before* the base letter that they are to be applied to is pressed - and at that point there is no "text" in a "buffer" so the accent key is forgotten about,,,?
