### ISSUE TITLE
Clazy analysis suggests that `(virtual bool) texteditorcontroller::readonly()` is possibly mismarked as a slot

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#136]
https://github.com/edbee/edbee-lib/blob/2bb98d28095db03df403d67d2f9a4934470fb7de/edbee-lib/edbee/texteditorcontroller.h#L151

For reference: https://github.com/KDE/clazy/blob/1.11/docs/checks/README-const-signal-or-slot.md

I also note that a couple of lines above there is also `(virtual bool) executeCommand( const QString& name=QString() );` - but I can't see how a non-void method would be usable as a **slot** so that looks bogus to me as well.

**Comment by SlySven** [comment]
Given the way that Qt's signals and slots work (*signal*s broadcast their arguments to any *slot* that has been `connect`ed to them {though it is fine if nothing has been attached - or the receiver has "gone-away" since the connection - the `QObject` code normally takes care to `disconnect` things in that case} but the process is one-way in that a slot does not feed back to the signal) I think that it is unreasonable for a slot method to have anything other than a `void` return.

It would probably be cleaner to have a slot "wrapper" that just calls the `(bool) TextEditorController::executeCommand(const QString&)` method and discards the return value...

:man_shrugging:

**Comment by gamecreature** [comment]
@SlySven I agree. Thought if I change this, it's a breaking change.

They way to do it (I guess) is to make the method return void. This has the least impact. 
I expect this return value isn't used. (It's not very useful)

**Comment by gamecreature** [comment]
@SlySven Just changed the type to void
