### ISSUE TITLE
forward declaration of ‘class edbee::TextEditorScrollArea’

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#15]
It would seem `/edbee-lib/edbee-lib/edbee/texteditorwidget.h` has to include the header `#include "views/texteditorscrollarea.h"` if you want to make use of `widget->textScrollArea()->enableShadowWidget(bool)`, otherwise the compiler does not like the setup:

> ../3rdparty/edbee-lib/edbee-lib/edbee/texteditorwidget.h:23:7: note: forward declaration of ‘class edbee::TextEditorScrollArea’
> class TextEditorScrollArea;

**Comment by gamecreature** [comment]
I'm not a fan of this...
If you want to use the TexteditorScrollArea you should include this header file. (less compile time etc)

Maybe I need to make a general include file that can be used to include everything.
For example:  #include "libedbee.h"

**Comment by vadi2** [comment]
Yep you're right, didn't think it through - just including the declaration in my files fixed it.
