### ISSUE TITLE
non-BMP characters require two keystrokes

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#19]
If you paste something like 😂 into edbee and use the mouse to highlight and delete it, it works fine. However if you try to use the backspace key, you'll need two backspaces in order to delete it. Same with just pressing the 'left' key to navigate to the left of the symbol - it requires two presses:

![peek 2017-06-02 06-25](https://cloud.githubusercontent.com/assets/110988/26710727/8d3eb6a0-475c-11e7-9c87-9b0bde312fdb.gif)

**Comment by gamecreature** [comment]
This one is pretty Complex. 
QChar, the base character in the editor, is a 16-bit unicode Character.
Which means emoticons (and some other codepoints) consist of 2 character in stead of 1.

**Comment by vadi2** [comment]
@slysven might have good input on this - we're implementing exactly the same thing in our custom widgets right now in Mudlet. Treating each character as a grapheme seems to be the way to go in Unicode.

**Comment by gamecreature** [comment]
The CharTextBuffer has a 'LineOffsetVector' list which remembers all 'lines' 
In combination with QTextBoundaryFinder..  
It's probably possible to do some smart stuff in the CharTextBuffer, for handling these situations.

But it's still a lot of work to fix it... 
You loose all easy-stuff, like simply getting the length of things for finding the number of characters etc

**Comment by vadi2** [comment]
Yeah that's the reality of working with Unicode unfortunately. I found [this post](https://blog.daftcode.pl/fixing-unicode-for-ruby-developers-60d7f6377388) to be very useful - it touches what you mention about getting the length of things.

**Comment by gamecreature** [comment]
Problem is now I have a giant buffer with Characters. (Via the GapVector). Every character has the same size, when a character can be made of of multiple elements, there are a lot of issues to solve, related to caret movement, length calculations, merging of string etc etc...

There are several solutions for this problem:
- just use bigger Characters (32 bits). 
- combine it with a shadow structure, which stores the extra bytes (Via SparseArray or something alike)
 
This requires some research

**Comment by gamecreature** [comment]
A work-around could be 'expanding' ranges. When An operation is going to be performed on a range, it should defect if it's in the middle of a special Unicode character and expand the range so the full character is selected..

**Comment by vadi2** [comment]
That's a good idea!

**Comment by SlySven** [comment]
I fear you are falling into the same issue that we have - the Unicode implementation in Qt is based on UTF-16 and like UTF-8 it is a __variable length encoding__ but unlike UTF-8 people forget that it can take more than one (and under some circumstances {e.g. Emoji character followed by a [variation selector](https://stackoverflow.com/q/4974668/4805858)} even a High/Low surrogate pair is not enough) base character unit(s) to describe even a _[grapheme](https://en.wikipedia.org/wiki/Grapheme)_.  Take a look at [What is Unicode, UTF-8, UTF-16?](https://stackoverflow.com/q/2241348/4805858) which has a good collection of links to other resources as well...!

_This may or may not appear as one glyph depending on whether your browser merges this: 
👨🏾‍🔬 {the Man Scientist: Medium-Dark Skin Tone glyph} into one glyph or leaves it as two or three separate ones (in my browser it shows a mid-brown skin tone man with a separate microscope but the full rendering should show him in a white coat) - anyhow that is definitely more that one UTF-32 code-point - of course in a text editor would use the "text rendered" form of three codepoints that sort of show individually as "👨 🏾‍ 🔬︎︎︎︎" which I think ought to be [forced into action with a suffixed U+FEOE codepoint](https://stackoverflow.com/q/32915485/4805858) as that is not likely to need the fully rendered representation - but people may wish to enter it and expect selection/cut/copy/paste to work on the entity as a whole._

**Comment by gamecreature** [comment]
I added a quick-hack for improved caret movement for non-BMP characters. 
It's very basic you can still set the caret in between the characters, but moving and selecting with the current commands seems to work correctly

**Comment by vadi2** [comment]
Confirmed fixed, thanks!
