### ISSUE TITLE
Rendering refresh error

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#23]
Best explained with a gif using the latest edbee-app:

![peek 2017-06-03 10-57](https://cloud.githubusercontent.com/assets/110988/26752237/7eb9de44-484b-11e7-9a4e-1fa5de9f7c68.gif)

Text I used with Lua syntax highlighting:

```lua
function mudletOlderThan(version)
	-- strip trailing zeros
  local stripped = rex.gsub(version, [[(\.0+)+$]], ''):split(.)
	display(stripped)
end

mudletOlderThan("2.5.10.4159")
mudletOlderThan("1.0.0")
mudletOlderThan("0.5")
mudletOlderThan("0.4.1")
mudletOlderThan("1")
mudletOlderThan("1.1")
mudletOlderThan("0.0.0")
mudletOlderThan("2.5.0")
mudletOlderThan("2")
mudletOlderThan("0.0")
mudletOlderThan("2.5.10")
mudletOlderThan("10.5")
mudletOlderThan("1.25.4")
mudletOlderThan("1.2.15")
```

**Comment by gamecreature** [comment]
I've been debugging this issue and the scope-invalidating optimisation is  wrong. It doesn't update scopes after the current text replace correctly. ( GrammarTextLexer::textChanged)

I'm going to fix it for now, by simply 'removing' all scoped info after the current line. This will fix the issue, but I need to rethink the optimised scope building.

**Comment by vadi2** [comment]
Works, thanks!
