### ISSUE TITLE
Brilliance themes corrupt painting

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#27]
![peek 2017-06-11 15-37](https://user-images.githubusercontent.com/110988/27011481-b949c282-4ebc-11e7-8675-2fd536c3985d.gif)

It looks very cool but I'm concerned it'll crash the application!

Attached are the two suspicious themes: [themes.zip](https://github.com/edbee/edbee-lib/files/1066459/themes.zip)

**Comment by gamecreature** [comment]
I think the cause of this is, is a none-opaque background: 
	<key>background</key>
	<string>#050505FA</string>

Alpha channels of the backgorund is FA.. 
Edbee doesn't clear the background it fills the background with the background color..
So painting with an transparent color, will behave like this...

I can fix this by forcing the background color opaque

**Comment by vadi2** [comment]
That seems like a good idea.

**Comment by gamecreature** [comment]
While debugging this issue. I noticed the uses the following hex-codes for colors
For example:
```xml
	<key>selection</key>
	<string>#0010B499</string>
```

Edbee uses the QColor::setNamedColor parser to parse the color hex-codes
QColor asssumes the hexcode are #AARRGGBB

But in the example above it looks like #RRGGBBAA is used.
(I can't imagine a theme maker wanted a invisible selection color)

**Comment by gamecreature** [comment]
I fixed the RGBA parsing issue and made the background color opaque.
I hope this fixes this rendering issue!

**Comment by vadi2** [comment]
Oh wow, great catch!

The painting is no longer corrupted so I'm happy. Thank you!
