### ISSUE TITLE
Theme changing without TextThemeManager::setTheme() called

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#29]
I'd like to have a function that I can use to warm up TextThemeManager's theme cache with, so I copy/pasted one to just load the theme without setting it:

```cpp
/// This method just loads the given theme file.
/// The theme manager stays owner of the given theme
/// @param filename the filename of the theme to load
/// @param name the name of the theme (if the name isn't given the basename of the fileName is used (excluding the .tmTheme extension)
/// @return the loaded theme or 0 if the theme couldn't be loaded
TextTheme* TextThemeManager::loadThemeFile( const QString& fileName, const QString& nameIn )
{
    lastErrorMessage_.clear();
    // check if the file exists
    QFile file(fileName);
    if( file.exists() && file.open(QIODevice::ReadOnly) ) {
        // parse the theme
        TmThemeParser parser;
        TextTheme* theme = parser.readContent(&file);
        if( theme ) {
            // when the name is blank extract it from the filename
            QString name = nameIn;
            if( name.isEmpty() ) {
                name = QFileInfo(fileName).completeBaseName();
            }
            themeMap_.insert(name,theme);
        } else {
            lastErrorMessage_ = QObject::tr("Error parsing theme %1:%2").arg(file.fileName()).arg( parser.lastErrorMessage());
        }
        file.close();
        return theme;
    } else {
        lastErrorMessage_ = QObject::tr("Error theme not found %1.").arg(file.fileName());
        return 0;
    }
}
```

Or so I thought. Somehow the theme is still being changed when `qApp->processEvents()` is run after my function! This is even without `TextThemeManager::setTheme() ` being touched at all.

Any ideas on what could be causing this?

**Comment by gamecreature** [comment]
How do you mean the Theme is still being changed? 
Is a second call reloading the given Theme?  Do you have some sample code?

The TextEditorController set the theme in it's contructor:
```c++
    textRenderer_->setThemeByName( textDocument()->config()->themeName() );
```

Is the name that's used in the TextDocumentConfig a name that has been loaded?

**Comment by vadi2** [comment]
I had a think about this and decided it was a terrible case of premature optimisation. I went a different route that avoids this problem altogether by _not_ caching all the themes and thus not incuding the lag upon loading them all, instead individually as needed ondemand. Sorry for the trouble!

**Comment by gamecreature** [comment]
No problem! 
Everybody falls in the optimisation trap now and then 😄
