### ISSUE TITLE
How to do search selection without actually selecting text for editing?

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#31]
Sublime allows selecting, or highlighting searched text of sorts without the text actually being selected for editing when you use the 'search in all open files' option. Is this possible in edbee?

**Comment by gamecreature** [comment]
Do you mean this kind of selection (Which isn't the true selection?)

![schermafbeelding 2017-06-24 om 13 56 42](https://user-images.githubusercontent.com/577933/27508431-f82d1ce2-58e4-11e7-970a-14a9011db764.png)

**Comment by gamecreature** [comment]
At the moment edbee only renders the current selection ...

You can control the complete rendering yourself, by subclassing the TextEditorRenderer class and give make edbee use the new renderer via:

```c++
widget->textEditorComponent()->giveTextEditorRenderer( .. )
```

It is an that edbee can support this by default (painting extra regions with borders like sublime does).
With an extra TextRangeSet that can be set.

btw. To find textranges in edbee editor, you can use the TextSearcher class, which supports regexp searching and multiple selections.

**Comment by gamecreature** [comment]
I've just implemented TextEditorController::borderedTextRanges...
Just add ranges here and you will see the same kind of non-selected ranges in the editor widget..
Edbee-App has been updated to, so it marks the current search wordt. (Liver while editing the search term)

Example for the FindWidget in the edbee app:
```c++
void FindWidget::textChanged(const QString &text)
{
    edbee::TextEditorController* controller = editorRef_->controller();
    edbee::TextSearcher* searcher = controller->textSearcher();
    searcher->setSearchTerm(text);
    searcher->markAll(controller->borderedTextRanges());
    controller->update();
}
```

**Comment by gamecreature** [comment]
This is a quick solution for, rendering special areas.
Perhaps for the future I need to support multiple ranges like these, with for example different rendering strategies..

**Comment by vadi2** [comment]
Perfect! Thanks so much :)
