### ISSUE TITLE
error: multiple definition of `edbee::pause_memleak_detection(bool)'

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#36]
It seems to be defined in both [debug.h](https://github.com/edbee/edbee-lib/blob/master/edbee-lib/edbee/debug.h#L18) and [debug_new.cpp](https://github.com/edbee/edbee-lib/blob/master/edbee-lib/edbee/util/mem/debug_new.cpp#L121) and mingw 5.3.0 isn't having any of it.

**Comment by gamecreature** [comment]
It has been disabled for mingw. See issue #14.

What's the issue you are having at this moment?

**Comment by vadi2** [comment]
Well the issue is that it is exactly going to the `#else` in:

```cpp

#if defined(QT_DEBUG) && !defined(__MINGW32__)
    #include "edbee/util/mem/debug_new.h"
    /// This assert requires the inclusion of QApplication an QThread
    #define Q_ASSERT_GUI_THREAD Q_ASSERT(  qApp->thread() == QThread::currentThread( ) )
    #define Q_ASSERT_NOT_GUI_THREAD Q_ASSERT(  qApp->thread() != QThread::currentThread( ) )
#else
    #define Q_ASSERT_GUI_THREAD
    #define Q_ASSERT_NOT_GUI_THREAD
    namespace edbee {
        inline void pause_memleak_detection(bool) {}
    }
#endif
```

So it is defining `pause_memleak_detection` again when it is already defined in `debug.h`. I think you want to add an ifdef to debug_new.cpp not to define the function there if `defined(__MINGW32__)` ?

**Comment by gamecreature** [comment]
I've just committed a solution which doesn't define two pause_memleak_detection methods

**Comment by vadi2** [comment]
Works! Thanks so much!
