### ISSUE TITLE
Clicking in margin has seemingly abnormal behavior

### ISSUE THREAD

**Issue by dicene** [edbee/edbee-lib#39]
When you click in a line number in the margin it selects the appropriate line and places the cursor at the beginning of the next line, which is standard functionality in every editor I've used. The part that strikes me as strange is that the line number(s) you select via margin-clicking don't get highlighted, instead only having the line that the caret lands on selected.

I think I understand why it's being done that way(because it's just highlighting whichever line the caret is on), but it seems like the more appropriate behavior would be what an editor like QtCreator does:

If any text is highlighted, highlight all lines in which text is currently selected.
Else highlight the line that the cursor is currently on(this is what edbee seems to be doing in all cases, currently).

See screenshots below for comparison between the two methods:

edbee w/ no selection:
![image](https://user-images.githubusercontent.com/15068394/27766444-031c807a-5e9e-11e7-9e9c-c68cde8781ae.png)

QtCreator w/ no selection:
![image](https://user-images.githubusercontent.com/15068394/27766450-199f377a-5e9e-11e7-89f4-302694e928b4.png)

edbee w/ multiple lines selected(via margin clicking):
![image](https://user-images.githubusercontent.com/15068394/27766431-52fe2e82-5e9d-11e7-99d2-040f869bbfde.png)

QtCreator w/ multiple lines selected(via margin clicking):
![image](https://user-images.githubusercontent.com/15068394/27766441-ddf9d0d6-5e9d-11e7-94b7-d61eca25b93f.png)

**Comment by dicene** [comment]
Actually, the way the selection is done when dragging upwards through the margin seems a little strange as well. This is what happens when I click in the margin on line 4 and drag up to the top of line 1 in edbee:
![image](https://user-images.githubusercontent.com/15068394/27766463-8dee8176-5e9e-11e7-882b-5bd8c7f427d4.png)

And here's what it does in QtCreator:
![image](https://user-images.githubusercontent.com/15068394/27766466-9e6b2c98-5e9e-11e7-907d-9d287cfdea99.png)

And here's the same movement in Notepad++:
![image](https://user-images.githubusercontent.com/15068394/27766467-b202a01a-5e9e-11e7-9129-2b3d99783de2.png)

Not necessarily saying that the way edbee does it is necessarily wrong, but with something like this that the majority of editors do in the exact same way, it'd be useful to mimic that behavior for the sake of users seeing it behave consistent to how it works everywhere else.

**Comment by gamecreature** [comment]
Edbee now uses both rendering options in the sidebar:

![schermafbeelding 2017-07-03 om 15 06 21](https://user-images.githubusercontent.com/577933/27794166-42a3dcf2-6001-11e7-9ac3-f9e38141744b.png)

* line-numbers of lines with selections are bright (100% opacity)
* line-numbers which contain the caret are marked with a background-color (like before)
