### ISSUE TITLE
How does one undo the effect of edbee::TextSearcher::markAll(...) ?

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#40]
As a result of issue #31 we gained the ability to mark without actual selection with `(void) edbee::TextSearcher::markAll (TextRangeSet *rangeset)` but as a newbie to using `edbee-lib` it is not immediately obvious how after doing the following to "mark" a series of ranges:

    edbee::TextController controller = mpSourceEditorEdbee->controller();
    edbee::TextSearcher searcher = controller->textSearcher();
    searcher->markAll(controller->borderedTextRanges());
    controller->update();

one would then "clear" those "markings" without otherwise disturbing the document text, from looking at https://github.com/edbee/edbee-lib/commit/a15b3ca75f5c6a9e978849744ef89c47ca24f40b it does not seem possible to clear this by specifying a null argument to `edbee::TextSearcher::markAll(...)` so what needs to go in as an argument or is another method needed to remove those outline markings?

**Comment by gamecreature** [comment]
You can manipulate the 'borderedTextRanges' directly with the controller instance variable:

```c++
edbee::TextEditorController* controller = editor->controller();
controller->borderedTextRanges()->clear();
controller->borderedTextRanges()->addRange(10,4);
controller->update();  // required to repaint after changes
```
borderedTextRanges() returns a [TextRangeSet](https://github.com/edbee/edbee-lib/blob/master/edbee-lib/edbee/models/textrange.h#L198)

**Comment by SlySven** [comment]
Yeah - that _WorksForMe_!
