### ISSUE TITLE
How to add commenting shortcut?

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#41]
Is there any way to enable the commenting shortcut with Lua code?

**Comment by gamecreature** [comment]
I've found the location that defines comments... (It currently is hardcoded 😒 )

[edbee.cpp:100](https://github.com/edbee/edbee-lib/blob/master/edbee-lib/edbee/edbee.cpp#L100)

It doesn't contain a LUA comment. I will add this...

**Comment by vadi2** [comment]
That's ok, we'll only ever have Lua comments.

-- single line comments look like this

--[[multiline comments
look like this]]

**Comment by gamecreature** [comment]
I've just committed a library with lua embedded in the source file.
You can Always add extra comments via the following construct (This example is for lua)

```c++
DynamicVariables env = Edbee::instance()->environmentVariables();

env->setAndGiveScopedSelector( "TM_COMMENT_START", "-- ", "source.lua");
env->setAndGiveScopedSelector("TM_COMMENT_START_2", "--[[", "source.lua");
env->setAndGiveScopedSelector("TM_COMMENT_END_2", "--]]", "source.lua");
```

This is the TextMate way of doing it.. 
TM_COMMENT_START is for line comments
TM_COMMENT_START1 and TM_COMMENT_END1 is for block comments

**Comment by vadi2** [comment]
Got it, thanks!

Would you mind adjusting the default ending - it is just ]] sans the dashes.

Sitting in a place to Croatia ATM so will test in a week :)

**Comment by vadi2** [comment]
:+1: works!
