### ISSUE TITLE
TextDocumentSerializer should not close ioDevice

### ISSUE THREAD

**Issue by sebcaux** [edbee/edbee-lib#43]
TextDocumentSerializer should not close ioDevice because it is not the owner of ioDevice and some QIODevice does not allow to close it.
For example [QSaveFile](http://doc.qt.io/qt-5/qsavefile.html) (ideal for text editor), could not close device.

https://github.com/edbee/edbee-lib/blob/master/edbee-lib/edbee/io/textdocumentserializer.cpp#L93
https://github.com/edbee/edbee-lib/blob/master/edbee-lib/edbee/io/textdocumentserializer.cpp#L168

For me, this two lines should be removed. Thanks !

**Comment by gamecreature** [comment]
I agree... But I don't want to break the current Serialization interface. 

I guess, I should add two extra methods to the interface. For loading and saving files
without touching the open and close methods:

```c++
    bool loadWithoutOpening( QIODevice* ioDevice );
    bool saveWithoutOpening( QIODevice* ioDevice );
```

I'm not very keen on these method names... Suggestions?

**Comment by vadi2** [comment]
We'd be fine with adapting to the interface changes, might be doable if
other users agree too.

**Comment by sebcaux** [comment]
Thanks, it was the best solution without broken old code
