### ISSUE TITLE
Commenting shortcut does not work if cursor is on the last character in line

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#44]
Steps to reproduce:

1. move cursor all the way to end of a line
1. press `Ctrl+/`
1. nothing happens!

![peek 2017-07-28 11-06](https://user-images.githubusercontent.com/110988/28715169-22382dac-7397-11e7-9b56-67ebe1cbefea.gif)

**Comment by gamecreature** [comment]
Note: This problem only occurs on the list line in the file

**Comment by vadi2** [comment]
Thanks!
