### ISSUE TITLE
Ctrl-Insert/Shift-Insert doesnt work as they should.

### ISSUE THREAD

**Issue by slothmagi** [edbee/edbee-lib#45]
Hi,
In ancient ages, windows copy/paste was ctrl-insert / shift-insert.
and all windows programs support them.
can you implement them too?

Copy = Ctrl-C = Ctrl-Insert
Paste = Ctrl-V = Shift-Insert

Thanks in advance

**Comment by slothmagi** [comment]
Fixed in https://github.com/edbee/edbee-lib/pull/42

**Comment by slothmagi** [comment]
Sorry, not fixed yet

**Comment by gamecreature** [comment]
Could you please let me know if the new commit solves your issue.
(At the moment I don't have a Windows machine at hand, testing ctrl+shift insert on a mac seems to be  impossible)

**Comment by vadi2** [comment]
I think this introduced a regression - default keybindings in the right-click menu are the non-standard Insert-based ones:

![workspace 1_181](https://user-images.githubusercontent.com/110988/31306430-4b514c14-ab50-11e7-81af-5aeb5f47cadd.png)

Could the menu go back to Ctrl+C, Ctrl+V?
