### ISSUE TITLE
Is Onigmo necessary or would Oniguruma also work?

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#50]
For those not in the know [k-takata/Onigmo](https://github.com/k-takata/Onigmo) is a fork of [kkos/oniguruma](https://github.com/kkos/oniguruma).  However the latter is more likely to be available in GNU/Linux distributions (and is in Cygwin) so using it instead will make it easier to use a "system" version rather than having to include it in this (and other projects such as the one I code for) using this library... 😜

**Comment by vadi2** [comment]
A related question, Qt has regex natively now - is it possible to use that
implementation instead for even less dependencies?

**Comment by gamecreature** [comment]
I don't think the regex of Qt isn't as comprehensive as the Onigmo/oniguruma library.
The Textmate/Sublime regexp's  used in syntax files use the oniguruma syntax.

I've choosed the onigmo library because it's the fork that's used int the Ruby language. Which hash some extra extensions

**Comment by gamecreature** [comment]
@SlySven do you have a suggestion how to support both situations?

**Comment by SlySven** [comment]
At a guess it would probably require `#ifdef`ed code around any code to support any difference in the API but at this time I am not familiar with either regular expression library to say (Mudlet uses a _Perl Compatible_ regexp IIRC - which although likely to do the same sort of thing has a different way of expressing _expressions_ ) ... 🙈 🙉 🙊

> I've choosed the onigmo library because it's the fork that's used int the Ruby language. Which has some extra extensions

I'm not entirely sure that Onigmo is the only option for Ruby but looking through the Ruby package on Debian shows that _it_ is not present as a package itself (whereas Oniguama is as [libonig](https://tracker.debian.org/pkg/libonig)).  Confusingly I checked and found that Ruby does not mention using Onigmo in its LEGAL file but only Onigurama - but I'll filed a bug report [there](https://bugs.ruby-lang.org/issues/13818) so perhaps that will get cleaned up. 🙂
