### ISSUE TITLE
Use of raw string literal causes issues when QT_NO_CAST_FROM_ASCII #defined

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#54]
In the declaration for `(virtual void) TextupdateStatusText(const QString&)` in `/edbee-lib/edbee/texteditorcontroller.h` the use of a raw `""` causes a compilation failure should an application include the `edbee-lib` widget and also `#define QT_NO_CAST_FROM_ASCII`.

This `#define` is used in order to locate `QStrings` that are initialised with raw string literals instead of being instantiated and marked as either:
+ to be part of the GUI and to be made _translatable_ with creation via calls to `QObject::tr(...)` or related methods
+ to marked as _internal_ and __NOT__ translatable with creation via `QStringLiteral(...)` or `QLatin1String(...)`

To correct this, simply modify the default value here:
https://github.com/edbee/edbee-lib/blob/c1ce1f18ba793174fdce23da6054bbdf726b119d/edbee-lib/edbee/texteditorcontroller.h#L108

to:

    virtual void updateStatusText( const QString& extraText=QString() );

**Comment by gamecreature** [comment]
I just found a second case in texteditorkeymap.h

```c++
TextEditorKeyMap* get( const QString& name=QString() );
```

**Comment by SlySven** [comment]
Ah, good - I hadn't got [Mudlet](http://github.com/mudlet/mudlet.git) to the stage where we can specify `#define QT_NO_CAST_FROM_ASCII` globally so wouldn't have failed at that point in the compilation (yet)...
