### ISSUE TITLE
Move line up/down commands should be available

### ISSUE THREAD

**Issue by gamecreature** [edbee/edbee-lib#56]
control + shift + up/down should take the current selected line and move it up/down

**Comment by gamecreature** [comment]
Fixed in commit: 432815edd2c3f623f30a25d8a840ac400e7b605e

**Comment by sebcaux** [comment]
Great add-in, thanks.
Only one point that should be improve is the undo of this command. If you move three times one line up for example, you should undo it three times also. Maybe these three similar command be grouped, no?

**Comment by gamecreature** [comment]
@sebcaux, you're right. I fixed this
