### ISSUE TITLE
Shift+Delete should perform a cut

### ISSUE THREAD

**Issue by gamecreature** [edbee/edbee-lib#59]
Similar to issue #45

**Comment by gamecreature** [comment]
Hmmm Shift+Delete already was used by another command... (Delete Right)

**Comment by gamecreature** [comment]
https://stackoverflow.com/questions/46220035/sublime-text-3-disable-shift-delete-copying-the-selected-text

It seems that Shift+Delete on all platforms except Mac is a cut
On the Mac it's a delete right

**Comment by vadi2** [comment]
Never knew it was a thing honestly

**Comment by gamecreature** [comment]
It isn't.... 
I just found out I read the keymap wrong.. 
Shift+Delete was just mapped as a normal Delete. I just removed it and removed the duplicate binding.. 
So problem is fixed ☺️

**Comment by vadi2** [comment]
Haha.

Feel like working on LSP support to make edbee even more awesome? :)

**Comment by gamecreature** [comment]
That would be a nice feature. Still need to figure out how to embed it ....
(And find some time for it, which is the biggest obstacle)

Also there are some other obstacles that need to be first.
Like there isn't any autocompletion support yet.
