### ISSUE TITLE
edbee-test expects theme at root level under Linux

### ISSUE THREAD

**Issue by keneanung** [edbee/edbee-lib#6]
When running `edbee-test` under Linux, it expects the theme at `/Monokai.tmTheme`. Putting random files into the root folder is probably not a good idea.

**Comment by gamecreature** [comment]
Also on windows or OS X this isn't a good idea...
The problem is that the TextThemeManager tries to load the current theme from the Theme folder.
If the theme folder hasn't been set, it shouldn't attempt to open the theme.

**Comment by vadi2** [comment]
We're going to install a default theme as part of the qt resource file, ensuring it is always available. I'm not sure if it's something `edbee-lib` has access to, but it's a good idea.
