### ISSUE TITLE
Autocomplete support

### ISSUE THREAD

**Issue by gamecreature** [edbee/edbee-lib#60]
Entering text should quickly display a menu like the one below.
Showing all symbols/words/keywords..
Can be confirmed with enter or closed with esc

![image](https://user-images.githubusercontent.com/577933/31658539-92284c4e-b331-11e7-8ee4-f19c6939a04e.png)

**Comment by gamecreature** [comment]
Autcomplete words should be pluggable
- autocomplete with used words
- autocomplete with keyword lists (optionally based on scope)
- autocomplete via langserver (in the future)
- custom autocomplete lists 
- ...

**Comment by vadi2** [comment]
Yes I'd love to see this, we'll definitely make use of it in Mudlet. We have some unfortunately-named functions like `registerAnonymousEventHandler()` which could use this.

**Comment by gamecreature** [comment]
![image](https://user-images.githubusercontent.com/577933/31947792-6d2f627a-b8d5-11e7-8cb9-93c8c1db9c8a.png)

**Comment by vadi2** [comment]
Nice, that's excellent! We'll look into integrating this soon.

**Comment by sebcaux** [comment]
Very good job! I will take a look, but for the moment I'm lookink to optimize and debug searching.
Does this system of auto completer provider could be compatible with contextual completion ? Compatibility with langserver will be a must!

**Comment by gamecreature** [comment]
Yes the system receives a caret-position and can use the TextDocumentScopes to 'know' the context. (Which language and which kind of scope)

**Comment by sebcaux** [comment]
Hi ! I finally try it. Globally it is a very good start.
Just two points that could be easily fixed :
- single click or double does not choose the item under cursor
- after clicking in the list and press enter to choose the world, editor lost focus

The integration and class choosen is very good. The idea to have a list of completer is pretty cool. We can use a global list for static worlds and another for dynamics one.

Good job

**Comment by gamecreature** [comment]
@sebcaux your two points should be solved.. 
And I've prevented mousewheel propagation to the editor window.

**Comment by sebcaux** [comment]
An include to QString is missing in edbee-lib/edbee/models/textautocompleteprovider.h, Qt 5.2 does not like that !
Interaction with TextEditorAutoCompleteComponent seems ok for now

**Comment by gamecreature** [comment]
@sebcaux  Fixed this in commit 199b8edb3786c18ca71e03357b3918a2ba45ad94

**Comment by gamecreature** [comment]
Created a new issues for TextDocument content autocmplete #64
