### ISSUE TITLE
Feature request: placeholderText for TextDocument

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#67]
Can there be the equivalent to this added to the `TextDocument` so that something can be shown instead (in a greyed-out, or perhaps customizable in some other way) when `TextDocument()->text()` would return an empty `QString`?

> # placeholderText : QString
>
> This property holds the editor placeholder text
>
> Setting this property makes the editor display a grayed-out placeholder text as long as the document() is empty.
>
> By default, this property contains an empty string.
> 
> ### Access functions:
> `QString placeholderText() const`
> `void setPlaceholderText(const QString &placeholderText)`

At present in Mudlet we display some helpful text when our script editor widget is used for a new item however once I get the I18n stuff up and running it will be difficult to show something in that place and change the language afterwards (and the text displayed should not actually be saved as content for that item anyway which makes using a placeholderText technique to show it better anyway!)

**Comment by Kebap** [comment]
I guess this isn't available, yet. 
Where in the API would you expect this added?

**Comment by gamecreature** [comment]
location: Is it  a document-based placeholder. Or view-based?
In theory you could have, multiple views of the same document. 
 
A the most simple solution would be make the view render a piece of text. (Which isn't scrollable).

**Comment by vadi2** [comment]
I'd say document?

**Comment by Kebap** [comment]
I'd say view? Not sure the exact difference.

Here is how Mudlet uses edbee, and how placeholders come into play.
We can display and edit multiple different documents in the widget. 
Some already have content to show, some are created brand new. 
Now the newly created files have some introductory comment.
You can see it take up the first five rows in the screenshot.
But this text should be turned into placeholder instead.
So they don't have to delete it first or just leave it in.
Instead as soon as they begin to type it vanishes.
This is before the document is done and saved.
Hope this makes the idea understandable... :)


![image](https://user-images.githubusercontent.com/117238/82124775-7bc10e80-97a1-11ea-896b-3c01c4d868ef.png)

**Comment by Kebap** [comment]
After diving through edbee codebase some more, TextEditorComponent and TextRenderer seem relevant.

**Comment by gamecreature** [comment]
I just added placeholder support. (Whenen TextDocument length is 0, the placeHolder textDocument is rendered instead, with a theme-less TextLayout).

**Comment by SlySven** [comment]
I think this can be closed now...
