### ISSUE TITLE
Data loss on ctrl+tab

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#72]
If I have text selected when I change the window and ctrl+tab back in, it is lost. Ctrl+Z does not undo the lost text either: https://streamable.com/9iom1

If I ctrl+tab out and back in, text stays OK. It's only when you click on another window and ctrl+tab back in that the data loss occurs.

**Comment by gamecreature** [comment]
I cannot simulate it on OS X. (Though Alt+Tab inserts a Tab Character, but it's undoable)

On Linux (Ubuntu 16) I CAN simulate it... 
It only happens on the second Alt+Tab.. (this is really strange)

But you can undo it when you press Ctrl+Z (or choose undo in the menu) many times...
🤔

**Comment by vadi2** [comment]
Oh I think I can't undo because we use a setDocument or something on focus loss.

**Comment by gamecreature** [comment]
@vadi2 could you please check if this commit solves your issue.. 
(It's more or less a workaround for it)

**Comment by vadi2** [comment]
Didn't seem to help - issue still occurs...

**Comment by gamecreature** [comment]
Could you please assert you are NOT using the default keymap file which contains the following line:

```javascript
{ "keys": "Backtab", "command": "tab_back" }
```

See commit in edbee-data: https://github.com/edbee/edbee-data/commit/783dac326d397fdbde0ca3ca1d18419b356638c2

**Comment by vadi2** [comment]
How would I check? I don't think we have a separate file so we are.

And actually, using a separate file would allow people to use their own keybindings, wouldn't it...

**Comment by gamecreature** [comment]
I looked through the code of Mudlet, but you don't seem to use an external keymap file
So I don't really now what's going wrong..
