### ISSUE TITLE
[Fatal-Bug] Using backtab on empty document causes Q_ASSERT failure

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#79]
We have discovered that if the document in the edbee-lib widget is empty and a back-tab is sent from the keyboard then this causes an assert failure at the second Q_ASSERT in `CharTextBuffer::charAt(int)` in the `chartextbuffer.cpp file:

```C++
/// Returns the character at the given character
/// @param offset the offset of the given character
/// @return the character at the given offset
QChar CharTextBuffer::charAt(int offset) const
{
    Q_ASSERT(offset >= 0);
    Q_ASSERT(offset < buf_.length() );
    return buf_.at(offset);
}
```

This is because at the following location: https://github.com/edbee/edbee-lib/blob/d6a71925bda26dcab2b32571b14338ffb7a18e2e/edbee-lib/edbee/commands/tabcommand.cpp#L74 an attempt is made to index (with `(QChar) TextDocument::charAt(int idx)`) into an empty `TextDocument` instance...

As it is causing a fatal termination this is a significant bug for us - and the invocation mechanism could be a bit too likely (using keyboard navigation around a dialogue containing a `edbee-lib` widget).

BTW Is there a way to tab in and out of such a widget and not have the `<Tab>`/`<Backtab>` (usually seen as a `<Tab>` with a `<Shift>` *key-modifier*) treated as a command input to the `edbee-lib` widget?

**Comment by SlySven** [comment]
There has not been any changes to the two files concerned (`./edbee-lib/edbee-lib/edbee/models/textdocument.cpp` and `./edbee-lib/edbee-lib/edbee/commands/tabcommand.cpp`) between the current upstream master (https://github.com/edbee/edbee-lib/commit/d6a71925bda26dcab2b32571b14338ffb7a18e2e) and our current version (https://github.com/dicene/edbee-lib/commit/1596623f57f34d3edd6165e18152c87215f4fe92) so I don't think this is anything we have done...! :relieved:

**Comment by gamecreature** [comment]
Yes, It's a bug in edbee-lib. Just fixed it.
Thanks for finding it!
