### ISSUE TITLE
Resources acquired but not released

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#94]
Check out this lgtm query for resources acquired but not released in destructor: https://lgtm.com/query/4595774969870185531/

Seems like a low issue, but an issue nonetheless?

**Comment by gamecreature** [comment]
I have't touched the TextLineData resource issue. It seems to be intentionally that way:

https://github.com/edbee/edbee-lib/blob/85f3a14cf14dae597ee917b7bf5908a71b88c073/edbee-lib/edbee/models/textlinedata.cpp#L23-L28

**Comment by vadi2** [comment]
Not sure what that means. Is that an issue in edbee or mudlet's use of it?

**Comment by gamecreature** [comment]
Does Mudlet use custom TextLineData items?
If not you can ignore it...

I don't really know anymore why this is done this way.

**Comment by vadi2** [comment]
I don't think so. OK, thanks for looking at this :)
