### ISSUE TITLE
Implement read only feature

### ISSUE THREAD

**Issue by brupelo** [edbee/edbee-lib#96]
@gamecreature Rick, hi again... how you doing? I hope you're alright.

Here's the thing, I've got my interest back on your project and I was wondering... how difficult would be implementing a setReadOnly feature similarly to other text editors such as Scintilla?

Could you please describe how much effort would be to get it done? I'd be willing to give it a shot if not very difficult but I'd need to know exactly the proper steps to do it correctly.

Thanks in advance!

Ns. I've see your amazing project has been stuck for few months, are you not actively developing anymore?

**Comment by gamecreature** [comment]
No the project is not dead. It's just that I don't have enough time for it at the moment.

Implementing readonly shouldn't be very hard. There's only entry point for changing the text document. Maybe I've implemented it earlier in an internal project which uses edbee. I will check that out.

**Comment by emoon** [comment]
I'm interested in this feature as well.

**Comment by gamecreature** [comment]
Just pushed en implemented readonly mode to master.
Use controller->setReadonly(true) or widget->setReadonly(true)

There's also a toggleReadonly command 'toggle_readonly': (See sample implementation of the edbee app context menu)
https://github.com/edbee/edbee-app/blob/843b3d9093db769488dc0059510015e13a3eeb68/edbee-app/ui/mainwindow.cpp#L904-L907


```c++
QAction* readonlyAction = controller->createAction( "toggle_readonly", tr("Toggle Readonly"), QIcon(), menu ) ;
readonlyAction->setCheckable(true);
readonlyAction->setChecked(controller->readonly());
menu->addAction(readonlyAction);
```
